# This is the simple Travis configuration, which is intended for use
# on applications which do not require cross-platform and
# multiple-GHC-version support. For more information and other
# options, see:
#
# https://docs.haskellstack.org/en/stable/travis_ci/
#
# Copy these contents into the root directory of your Github project in a file
# named .travis.yml

# Use new container infrastructure to enable caching
sudo: false

dist: trusty

# Do not choose a language; we provide our own build tools.
language: generic

matrix:
  include:
    - env: STACK_YAML=stack-travis-ghc-8.2.yaml GHCVER=8.2.1 FLAGS="--haddock --no-haddock-deps --flag toysolver:BuildToyFMF --flag toysolver:BuildSamplePrograms --flag toysolver:BuildMiscPrograms --flag toysolver:TestCBC --flag toysolver:TestGlpsol --flag toysolver:TestLPSolve --flag=toysolver:OpenCL" RELEASE=1
      compiler: ": #GHC 8.2.1"
      addons: {apt: {packages: [libgmp-dev,coinor-cbc,glpk-utils,lp-solve,c2hs,ocl-icd-opencl-dev]}}
    - env: STACK_YAML=stack-travis-ghc-8.2.yaml GHCVER=8.2.1 FLAGS="--flag toysolver:BuildToyFMF --flag toysolver:BuildSamplePrograms --flag toysolver:BuildMiscPrograms --flag=toysolver:OpenCL"
      compiler: ": #GHC 8.0.2"
      os: osx
    - env: STACK_YAML=stack-travis-ghc-8.0.yaml GHCVER=8.0.1 FLAGS="--coverage --flag toysolver:BuildToyFMF --flag toysolver:BuildSamplePrograms --flag toysolver:BuildMiscPrograms --flag toysolver:TestCBC --flag toysolver:TestGlpsol --flag toysolver:TestLPSolve --flag=toysolver:OpenCL" COVERAGE=1
      compiler: ": #GHC 8.0.2"
      addons: {apt: {packages: [libgmp-dev,coinor-cbc,glpk-utils,lp-solve,c2hs,ocl-icd-opencl-dev]}}
    - env: STACK_YAML=stack-travis-ghc-7.10.yaml GHCVER=7.10.3 FLAGS="--flag toysolver:BuildToyFMF --flag toysolver:BuildSamplePrograms --flag toysolver:BuildMiscPrograms --flag toysolver:TestCBC --flag toysolver:TestGlpsol --flag toysolver:TestLPSolve --flag=toysolver:OpenCL"
      compiler: ": #GHC 7.10.3"
      addons: {apt: {packages: [libgmp-dev,coinor-cbc,glpk-utils,lp-solve,c2hs,ocl-icd-opencl-dev]}}
    - env: STACK_YAML=stack-travis-ghc-7.8.yaml GHCVER=7.8.4 FLAGS="--flag toysolver:BuildSamplePrograms --flag toysolver:BuildMiscPrograms --flag toysolver:TestCBC --flag toysolver:TestGlpsol --flag toysolver:TestLPSolve --flag=toysolver:OpenCL"
      compiler: ": #GHC 7.8.4"
      addons: {apt: {packages: [libgmp-dev,coinor-cbc,glpk-utils,lp-solve,c2hs,ocl-icd-opencl-dev]}}

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- |
  if [ `uname` = "Darwin" ]; then
    travis_retry curl -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 -C ~/.local/bin '*/stack'
  else
    travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  fi  

install:
# Build dependencies
- stack --stack-yaml=$STACK_YAML --jobs 2 --no-terminal --install-ghc build --test --bench --only-dependencies $FLAGS

script:
# Build the package, its tests, and its docs and run the tests
- stack --stack-yaml=$STACK_YAML --jobs 2 --no-terminal test --bench --no-run-benchmarks $FLAGS

after_script:
- "[ -n \"$COVERAGE\" ] && travis_retry curl -L https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.4.0/shc-linux-x64-$GHCVER.tar.bz2 | tar -xj"
- "[ -n \"$COVERAGE\" ] && ./shc toysolver TestSuite TestPolynomial"

before_deploy:
- stack --install-ghc runghc --package turtle misc/build_artifacts.hs

deploy:
  provider: releases
  api_key:
    secure: "WhAyiMHX+EGKdlECuT7sEqTzHOWqmnDB2DSS370ugApFklj1k8yLUp4sC1myFAxaNJYAlWRWV9ciJO/+zi/SOEmFp4+JAiNNfwVokugjqc2qeqr5NG5EGH9hqv8Sp67LBGAmvmFRZuFZ2f/0hLaBmsI8++HJJG4IBCHlBhN+XCY="
  file_glob: true
  file: '*.tar.xz'
  skip_cleanup: true
  on:
    tags: true
    condition: "$RELEASE = 1"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d83a1749bd96e9513d76
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
